### ISSUE TITLE
The container registry being used doesn't allow for public API access.

### ISSUE THREAD

**Issue by danielscholl** [danielscholl/managed-platform-modules#5]
Currently the Azure Container Registry being used to host the modules in it has been set to have anonymous access enabled as defined in the [document](https://learn.microsoft.com/en-us/azure/container-registry/anonymous-pull-access).

However the API is not returning results and is saying authentication is necessary still.

https://managedplatform.azurecr.io/v2/bicep/platform/container-registry/tags/list

**Comment by Miller-Kyle** [comment]
ACR only allows you to get tags with basic authentication. I opened a ticket with Azure support to see if they can help us. In the meantime, I created a PR to pull module tags from GitHub itself.
